name: Publish NuGet Packages

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Get version from tag
        id: get_version
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          VERSION="${VERSION#v}" 
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore ./src/SuperSimpleQueue/SuperSimpleQueue.csproj

      - name: Build
        run: dotnet build ./src/SuperSimpleQueue/SuperSimpleQueue.csproj --configuration Release --no-restore

      - name: Pack with version
        run: |
          dotnet pack ./src/SuperSimpleQueue/SuperSimpleQueue.csproj \
            --configuration Release \
            --no-build \
            -p:PackageVersion=${{ env.VERSION }} \
            -o ./artifacts

          dotnet pack ./src/SuperSimpleQueue.Core/SuperSimpleQueue.Core.csproj \
            --configuration Release \
            --no-build \
            -p:PackageVersion=${{ env.VERSION }} \
            -o ./artifacts

      - name: Publish to NuGet
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
